### ISSUE TITLE
登录成功之后获取valiatekey 失败

### ISSUE THREAD

**Issue by aximo** [wmo-v/eastmoneyapi#2]
我采用java 来实现，登录成功,但是无法获取到validatekey, 如何让服务端知道 获取 key的请求和登录请求是同一个? 求教

**Comment by wmo-v** [comment]
这个 key 是放在服务端渲染后的 html 里面，用正则匹配，登录随便访问一个页面都有



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月7日(周四) 中午11:33
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [wmo-v/eastmoneyapi] 登录成功之后获取valiatekey 失败 (Issue #2)




 
我采用java 来实现，登录成功,但是无法获取到validatekey, 如何让服务端知道 获取 key的请求和登录请求是同一个? 求教
